# This must match CONFIG_MCUBOOT_SIGNATURE_KEY_FILE in prj.conf.
CONFIG_BOOT_SIGNATURE_TYPE_RSA=y
CONFIG_BOOT_SIGNATURE_KEY_FILE="/workspace/app/keys/root-rsa-2048.pem"
CONFIG_MCUBOOT_LOG_LEVEL_WRN=y
